In [49]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [50]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [51]:
df.shape

(569, 33)

In [52]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [53]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split


In [54]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scaling

In [55]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [56]:
X_train

array([[ 0.24474612, -0.00728287,  0.21674801, ...,  0.52959862,
         0.09789602,  0.04698073],
       [-1.00355053,  0.16883017, -1.00869347, ..., -0.7092114 ,
        -0.03145527, -0.3786275 ],
       [ 1.11409557,  0.62765098,  1.04031261, ..., -0.33775071,
        -0.87305736, -1.07817695],
       ...,
       [ 0.03019513,  1.08415452,  0.04855809, ...,  0.95955108,
         2.98292108,  1.09806847],
       [-0.01717326, -0.8044261 , -0.0840532 , ..., -0.48435994,
        -1.25456181, -0.98882274],
       [-1.16404581, -0.24827966, -1.09440564, ..., -0.22699617,
        -0.47190461,  1.89755355]])

In [57]:
y_train

291    B
245    B
197    M
262    M
557    B
      ..
296    B
121    M
214    M
439    B
176    B
Name: diagnosis, Length: 455, dtype: object

# Lable Encoder

In [58]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [59]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,

# Numpy arrays to PyTorch tensors

In [60]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [61]:
X_train_tensor.shape

torch.Size([455, 30])

In [62]:
X_train_tensor

tensor([[ 0.2447, -0.0073,  0.2167,  ...,  0.5296,  0.0979,  0.0470],
        [-1.0036,  0.1688, -1.0087,  ..., -0.7092, -0.0315, -0.3786],
        [ 1.1141,  0.6277,  1.0403,  ..., -0.3378, -0.8731, -1.0782],
        ...,
        [ 0.0302,  1.0842,  0.0486,  ...,  0.9596,  2.9829,  1.0981],
        [-0.0172, -0.8044, -0.0841,  ..., -0.4844, -1.2546, -0.9888],
        [-1.1640, -0.2483, -1.0944,  ..., -0.2270, -0.4719,  1.8976]],
       dtype=torch.float64)

In [63]:
y_train_tensor.shape

torch.Size([455])

# Defining The Model

In [64]:
class MySimpleNN():
  def __init__(self,X):

    self.weights=torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate loss
    loss = -(y_test_tensor * torch.log(y_pred) + (1 - y_test_tensor) * torch.log(1 - y_pred))
    return loss.mean()


In [65]:
learning_rate=0.1
epochs=25

# Training *Pipeline*

In [66]:
# Create a model
model=MySimpleNN(X_train_tensor)

# Desfine loop
for epoch in range(epochs):

# Forward Pass
    y_pred=model.forward(X_train_tensor)

# Loss calculate
    loss=model.loss_function(y_pred,y_train_tensor)

# Backward Pass
    loss.backward()

# Update weights
    with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad

# Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

# Print loss in each epoch
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.527511186116905
Epoch: 2, Loss: 2.4364923054251295
Epoch: 3, Loss: 2.348320684785682
Epoch: 4, Loss: 2.2633367441461645
Epoch: 5, Loss: 2.1806220774857548
Epoch: 6, Loss: 2.1008314995991646
Epoch: 7, Loss: 2.0243334541827323
Epoch: 8, Loss: 1.9511952360726368
Epoch: 9, Loss: 1.8823708245496207
Epoch: 10, Loss: 1.8177348042392807
Epoch: 11, Loss: 1.7582368934940205
Epoch: 12, Loss: 1.7037561878302503
Epoch: 13, Loss: 1.6541244966359976
Epoch: 14, Loss: 1.609111055159692
Epoch: 15, Loss: 1.5684153524523778
Epoch: 16, Loss: 1.5316759809649727
Epoch: 17, Loss: 1.4984929925968027
Epoch: 18, Loss: 1.4681096194538352
Epoch: 19, Loss: 1.4399842565177974
Epoch: 20, Loss: 1.4143408644292665
Epoch: 21, Loss: 1.3908116087986813
Epoch: 22, Loss: 1.3690762839223645
Epoch: 23, Loss: 1.3488193213719273
Epoch: 24, Loss: 1.3295710167072583
Epoch: 25, Loss: 1.3114408271856401


In [71]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.8).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5572484135627747
