In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")

CUDA is available.
Device name: Tesla T4


Create Tensor

In [5]:
a=torch.empty(2,3)

In [6]:
a

tensor([[2.6508e-35, 0.0000e+00, 3.7837e-14],
        [4.5021e-41, 1.4013e-45, 0.0000e+00]])

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.8791, 0.6485, 0.0899],
        [0.3083, 0.0934, 0.2258]])

In [11]:
# Manual Seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.tensor([[1,2,2],[5,6,7]])

tensor([[1, 2, 2],
        [5, 6, 7]])

In [14]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [17]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [18]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [20]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [22]:
x.shape

torch.Size([2, 3])

In [23]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3977301040171529017]])

In [24]:
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

In [26]:
x.dtype

torch.int64